# Exception-Handling
Aim:
To study Exception handling in c++.

Theory:
Exceptions are runtime anomalies or abnormal conditions that a program encounters during its execution. Exception handling in C++ is a mechanism that allows a program to deal with unexpected or exceptional situations (such as runtime errors) in a structured way, ensuring that the program can continue functioning or terminate gracefully.

C++ provides the following specialized keywords for this purpose:

try: Represents a block of code that can throw an exception.
catch: Represents a block of code that is executed when a particular exception is thrown.
throw: Used to throw an exception. When an exception is detected, control is transferred to the throw statement. The throw statement jumps to the appropriate catch block that handles the type of exception. Once caught, the catch block executes, after which the program can either recover or terminate based on the logic implemented.
Output:

1.divide by zero error:

![Screenshot 2024-10-11 123011](https://github.com/user-attachments/assets/8f17d931-3a9b-426f-8ab0-2c647a8ce8d3)

2.positive/negative number:

![Screenshot 2024-10-11 123137](https://github.com/user-attachments/assets/480a8b34-8546-4e87-b35f-bfcae850a4e7)

3.Year more than 2000

![Screenshot 2024-10-11 123219](https://github.com/user-attachments/assets/3a8dc468-df59-4894-88ca-643044734ea7)

Conclusion:
We learnt to implement try.catch and throw in exception handling.

